Network:
  batch_size: 8 # resnet
#  batch_size: 1 # ViT
#  lr: 5e-5 # mimic/chexpert imagenet
  lr: 1e-5 # vindr imagenet
  weight_decay: 0
  amsgrad: False
  num_epochs: 1000
  #num_epochs: 50000
network_output_path: network_data/
output_data_path: output_data/
tb_logs_path: tensor_board_logs/
stat_log_path: stat_logs
checkpoint_name: checkpoint.tar
trained_model_name: trained_model.pth

# changeable items:
file_path: /home/soroosh/Documents/datasets/XRay/
target_dir: /home/soroosh/Documents/Repositories_target_files/chestx_domain/
display_stats_freq: 1 # valid freq is equal to this
#display_stats_freq: 100 # valid freq is equal to this